# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_PASSWORD: "123456"
      MYSQL_USER: "cori_health"
      MYSQL_DATABASE: "cori"
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080